baseURL = "https://sage-s11.github.io/codename-pi/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "paige"

[params]
  description = "A Hugo blog using the Paige theme"
  showReadMore = true
